name: Deploy Laravel to Ubuntu Server

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_password
          POSTGRES_DB: podcast_speedster_testing
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U test_user -d podcast_speedster_testing"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      redis:
        image: redis:latest
        ports:
          - 6379:6379

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.4"
          extensions: mbstring, bcmath, ctype, fileinfo, json, pdo, pdo_pgsql, tokenizer, xml, redis
          tools: composer

      - name: Install Dependencies
        run: composer install --prefer-dist --no-progress --no-interaction --optimize-autoloader

      - name: Set Up Environment File
        run: |
          cp .env.ci .env
          php artisan key:generate
        env:
          DB_CONNECTION: pgsql

      - name: Run Migrations
        run: php artisan migrate --force

      - name: Run Tests
        run: php artisan test

      - name: Check Code Style
        run: composer pint-test

      - name: Run Static Analysis
        run: composer phpstan

  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ vars.HOST_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd ${{ vars.APP_PATH }}

            git pull origin main

            composer install --no-dev --prefer-dist --optimize-autoloader
            php artisan migrate --force
            php artisan config:clear
            php artisan route:clear
            php artisan view:clear

            chown -R ${{ secrets.SERVER_USERNAME }}:www-data ${{ vars.APP_PATH }}
            chmod -R 775 ${{ vars.APP_PATH }}/storage
            chmod -R 775 ${{ vars.APP_PATH }}/bootstrap/cache

            sudo supervisorctl reread
            sudo supervisorctl update
